# Generated by Django 2.0.9 on 2018-10-09 19:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181009_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 9, 19, 35, 34, 760698, tzinfo=utc)),
        ),
    ]
